# This updates the Web Installer with the files from the docs folder and the binary of the latest release
# it only gets run on:
#  - Changes to the docs folder in the `rolling` branch
#  - On a release

name: Manual Web Installer Update

on:
  repository_dispatch: # Run on manual trigger
#  push:
#    branches:
#    - rolling
#    paths:
#    - docs # The path filter somehow does not work, so lets run it on every change to rolling
      
jobs:
  manually-update-web-installer:    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Get version of last release
      id: last_release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }}
        exclude_types: "release"
        view_top: 1     
      
    - name: Add binary to Web Installer and update manifest
      run: |
        rm -f docs/binary/firmware.bin
        wget https://github.com/jomjol/AI-on-the-edge-device/releases/download/${{ steps.last_release.outputs.tag_name }}/AI-on-the-edge-device__update__${{ steps.last_release.outputs.tag_name }}.zip
        unzip AI-on-the-edge-device__update__${{ steps.last_release.outputs.tag_name }}.zip
        cp -f firmware.bin docs/binary/firmware.bin
        cp -f docs/manifest_template.json docs/manifest.json
        sed -i 's/VERSION/${{ steps.last_release.outputs.tag_name }}/g' docs/manifest.json

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1   
  
